version: '3'

services:
  # 資料庫
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: qwe123

  adminer:
    image: phpmyadmin:5
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=qwe123